[parity]
chain = "dev"

[account]
unlock = ["0xddf8430d91ca7cf8df175813b58865dff2e15bc6"] 
password = ["/root/.local/share/io.parity.ethereum/password.txt"]

[rpc]
hosts = ["all"]
interface = "all"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "parity_accounts", "personal"]

[websockets]
hosts = ["all"]
interface = "all"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "parity_accounts", "personal"]

[misc]
log_file = "/var/log/parity.log"
